#!/bin/bash

echo "=== Starmie Demo Commands ==="
echo "Dataset created in: data/demo/"
echo ""

echo "1. Pre-train the model:"
echo "CUDA_VISIBLE_DEVICES=0 python run_pretrain.py \\"
echo "  --task demo \\"
echo "  --batch_size 64 \\"
echo "  --lr 5e-5 \\"
echo "  --lm roberta \\"
echo "  --n_epochs 3 \\"
echo "  --max_len 128 \\"
echo "  --size 10000 \\"
echo "  --projector 768 \\"
echo "  --save_model \\"
echo "  --augment_op drop_col \\"
echo "  --fp16 \\"
echo "  --sample_meth head \\"
echo "  --table_order column \\"
echo "  --run_id 0"
echo ""

echo "2. Extract vectors:"
echo "python extractVectors.py \\"
echo "  --benchmark demo \\"
echo "  --table_order column \\"
echo "  --run_id 0 \\"
echo "  --save_model"
echo ""

echo "3a. Run linear search:"
echo "python test_naive_search.py \\"
echo "  --encoder cl \\"
echo "  --benchmark demo \\"
echo "  --augment_op drop_col \\"
echo "  --sample_meth head \\"
echo "  --matching linear \\"
echo "  --table_order column \\"
echo "  --run_id 0 \\"
echo "  --K 5 \\"
echo "  --threshold 0.7"
echo ""

echo "3b. Run LSH search:"
echo "python test_lsh.py \\"
echo "  --encoder cl \\"
echo "  --benchmark demo \\"
echo "  --run_id 0 \\"
echo "  --num_func 8 \\"
echo "  --num_table 100 \\"
echo "  --K 5"
echo ""

echo "3c. Run HNSW search:"
echo "python test_hnsw_search.py \\"
echo "  --encoder cl \\"
echo "  --benchmark demo \\"
echo "  --run_id 0 \\"
echo "  --K 5"